### ISSUE TITLE
Great Work!

### ISSUE THREAD

**Issue by Boar007** [tartanguru/alexa-assistant-instructions#1]
Hi
I'm from Germany and just installed the google assistant for alexa.
It works without any problems. Thanks a lot for this and the very good installation guide.

**Comment by tartanguru** [comment]
Thanks for taking the time to leave feedback. It's most appreciated

**Comment by m3lloa** [comment]
Have to 2nd that. The inability to search the internet was the first thing I missed @ Alexa. You've provided one of the most important feature one would need. Thanks 👍
