### ISSUE TITLE
Update certificate authorities for AVS client

### ISSUE THREAD

**Issue by unfassbarstephan** [tartanguru/alexa-assistant-instructions#10]
I received this e-mail message.

"[ACTION REQUIRED]
Update certificate authorities for your AVS client
Posted On: March 14, 2018

Alexa Developer:

The Alexa Voice Service is moving to Amazon Trust Services (ATS) certificates for all AVS endpoints. Because of this change, all Alexa-enabled devices and applications must support certificates vended from ATS by June 15, 2018. Your device or application will not be able to connect to AVS if it does not support ATS certificates after June 15, 2018.

We recommend testing that your device or mobile application successfully connects to AVS endpoints using ATS certificates. Please follow the instructions listed on the AVS Developer Forum to learn how to complete testing and upgrade support for ATS."

Would that be a problem in the future?

**Comment by tartanguru** [comment]
This has nothing to do with Alexa skills,  it is for third party Alexa
enabled devices
