### ISSUE TITLE
fix for The skill keeps asking me to link my Google Account not working

### ISSUE THREAD

**Issue by leenga12** [tartanguru/alexa-assistant-instructions#11]
I continually have to link my Google Account.  I've tried the fix listed in common issues several times but I still continue to have the issue.

**Comment by tartanguru** [comment]
I'm sorry but I don't have anything more to suggest that the fix in the
common issues as this has worked for everyone else that has reported this
problem

**Comment by sheriffdude** [comment]
if you go to the skilsl page on amazon look to see if you have 2 skills i had made a mistake the first time and redone this to get it to work but had not deleted the old 1 so i had to skill showing up for the same thing ..in Alexa Skills Kit Developer Console  i had 2 skills showing up

**Comment by leenga12** [comment]
Thanks both of you. I tried the fix several times and eventually it worked!
