### ISSUE TITLE
Setting up using the new ASK Developer Console

### ISSUE THREAD

**Issue by funkydan2** [tartanguru/alexa-assistant-instructions#13]
Wow - thanks for pulling this together. It's like magic.

I had a few issues getting everything to work with the new Alexa Developer Console, but I think I've worked it out now.

I spent a bit of time trying to work out the Interaction Model...and especially how to set up the SearchIntent. I think I've got it right now, and I've attached the JSON file which I think anyone could simply upload to the new developer console/skill builder.
![screen shot 2018-03-24 at 4 29 08 pm](https://user-images.githubusercontent.com/10623666/37861218-7bc91cc8-2f80-11e8-948e-bf5f28fb878d.png)

[alexa-assistant-interaction-model.json.txt](https://github.com/tartanguru/alexa-assistant-instructions/files/1844100/alexa-assistant-interaction-model.json.txt)

I also took a few screenshots along the way since the [fresh install](https://github.com/tartanguru/alexa-assistant-instructions/blob/master/fresh_install.md) instructions only reference the older console. If you think people would find it helpful I'd be happy to put the screenshots in the documentation.

**Comment by tartanguru** [comment]
Thanks for this. Unfortunately it is quite a few hours of work to update the instructions which i won't have time to do for a few weeks

**Comment by tartanguru** [comment]
If you are able to update the instructions with the new screen shots and then submit it as a Pull Request that would be most appreciated. If you don't know how to do that then maybe just stick the screen shots in a zip file and upload it here please

**Comment by funkydan2** [comment]
Ok, I'll see if I can get to a PR towards the end of this week.

**Comment by mattnourse** [comment]
Hey funkydan2, your screen shots woudl be a huge help, ive tried but am getting.....

There was a problem with the requested skills response. 

and on the spot screen it says the requested skill has not declared that it implements the display......

such a great skill, woud love it to work. 

Thanks in advance

**Comment by tartanguru** [comment]
You need to make sure that you have set up the skill to use render
templates - not sure how to do that on the new layout though

**Comment by funkydan2** [comment]
[Alexa Developer Console.zip](https://github.com/tartanguru/alexa-assistant-instructions/files/1953093/Alexa.Developer.Console.zip)

Hi @mattnourse, sorry I haven't had a chance to have a go at updating the documentation. This zip file is all the screenshots I grabbed on the way through. Hopefully, they'll help and I'll try to put them into the docs soon!

Though, I don't have an Echo Spot - so I don't know anything about where things are coming unstuck for you.

**Comment by mattnourse** [comment]
Quite easy actually! 

in interfaces, i had to enable display interface.

Thank you!

**Comment by mattnourse** [comment]
So its working, but i have to sign into google regularly. Alexa says theres a trouble shooting page about this? im struggling to find it.....

thanks in advance...

**Comment by tartanguru** [comment]
You can find the common issues page here:-

https://github.com/tartanguru/alexa-assistant-instructions/blob/master/common_problems.md

**Comment by tartanguru** [comment]
Closing this issue as the instructions have been updated for the new console

**Comment by gdkali** [comment]
> Wow - thanks for pulling this together. It's like magic.
> 
> I had a few issues getting everything to work with the new Alexa Developer Console, but I think I've worked it out now.
> 
> I spent a bit of time trying to work out the Interaction Model...and especially how to set up the SearchIntent. I think I've got it right now, and I've attached the JSON file which I think anyone could simply upload to the new developer console/skill builder.
> ![screen shot 2018-03-24 at 4 29 08 pm](https://user-images.githubusercontent.com/10623666/37861218-7bc91cc8-2f80-11e8-948e-bf5f28fb878d.png)
> 
> [alexa-assistant-interaction-model.json.txt](https://github.com/tartanguru/alexa-assistant-instructions/files/1844100/alexa-assistant-interaction-model.json.txt)
> 
> I also took a few screenshots along the way since the [fresh install](https://github.com/tartanguru/alexa-assistant-instructions/blob/master/fresh_install.md) instructions only reference the older console. If you think people would find it helpful I'd be happy to put the screenshots in the documentation.

still, I'm facing the same problem

**Comment by JaredZA11** [comment]
Anyone manage to successfully get this working in the last year?

**Comment by bhafer** [comment]
> 
> 
> Anyone manage to successfully get this working in the last year?

No. The project is abandoned apparently.
