### ISSUE TITLE
shouldEndSession

### ISSUE THREAD

**Issue by davikhale** [tartanguru/alexa-assistant-instructions#14]
Is there any development that can be done to allow multiple requests to be made using the same utterance?

"Google, whats the weather... 'answer, stay open' "Google, when is it supposed to rain"

Using shouldEndSession: false?

If this is not possible, that is fine - just curious.

Thanks,

**Comment by tartanguru** [comment]
The skill follows the direction of the Assistant API as to whether it is expecting a follow on response. If you live in the US then the new Alexa Follow On mode setting may solve this, but I can't test as I'm in the UK

**Comment by tartanguru** [comment]
Closing this issue as it is associated with the skill and not this project which is just for the instructions.
This particular request is already logged in the skill project here:-
https://github.com/tartanguru/alexa-assistant/issues/49
