### ISSUE TITLE
CloudFormation Template doesn't work for Language "English (Australia)"

### ISSUE THREAD

**Issue by syphe** [tartanguru/alexa-assistant-instructions#2]
Have gone through all the steps up to and including setting up the CloudFormation stack, which is where it gets stuck, there is validation within the CloudFormation template which is checking the region to make sure it's either US East/EU West.

For the language "English (Australia)", you must host your lambda function on the Oregon servers.

**Comment by tartanguru** [comment]
You only need to host your lambda function in a specific region if you
utilise the geographical endpoints option in the skill which the skill
doesn’t.
The skill will still work in Australia by selecting either US East/ EU West
- I have lots of reports of Australian users installing the skill without
issue

**Comment by syphe** [comment]
thanks, I gave it another try this morning linking my AU skill to the EU lambda, and it seemed to work, without giving me the same error that I was getting yesterday.
