### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by chucka1** [tartanguru/alexa-assistant-instructions#3]
How can I set location on Google assistant/alexa to my location, when I ask question it gives information based on Dublin

**Comment by tartanguru** [comment]
It tells you how to do this using the Google Assistant app on your phone at
the end of the instructiosn

**Comment by chucka1** [comment]
Thank you. I am a complete technophobe, it took me 5 attempts to put google on alexa but I got there in end, did not read your instructions on Json correctly. I have old 4.2 on phone so I wil attempt to put 6.0 on to load google assistant. I am at moment downloading 7.0 onto tablet to try and put google assistant on there. I can only learn by my mistakes !! Hopefully
