### ISSUE TITLE
Location not updating after changing this in Google Assistant

### ISSUE THREAD

**Issue by Dunc-2014** [tartanguru/alexa-assistant-instructions#4]
Hi,

Just hoping you can help really. I've followed you very helpful and straight forward guide to add Google to Alexa but even though I have changed the location in Google Assistant it still thinks I'm in Dublin. I've tried unlinking by google account and relinking but it's still the same.

Can you help me change this?

Many thanks
Duncan

**Comment by tartanguru** [comment]
Hi Duncan,

I'm afraid this seems to be an an issue at the Google end rather than the
skill.
My only recommendation is to follow the process in the problem solving
guide for fully unlinking your account and see if that addresses the issue

Ross

**Comment by Dunc-2014** [comment]
Hi Ross,

Thank you. Yes, didn't think it was an issue your side but just wondered if you'd heard of this issue before. I'll give it another go.

Thanks again
Duncan
