### ISSUE TITLE
Error message when linking google account

### ISSUE THREAD

**Issue by liam4244** [tartanguru/alexa-assistant-instructions#7]
hi there, i have completed all the steps and checked i have done all correctly but am getting the attached error message every time i try to link my alexa app with google account.

Please help. I am stuck. 
[Doc1.docx](https://github.com/tartanguru/alexa-assistant-instructions/files/1770881/Doc1.docx)

**Comment by tartanguru** [comment]
Hi,

Can you repost the error message as an image as I'm not going to open a
Word document from somebody I don't know - sorry

Ross

**Comment by liam4244** [comment]
[cid:1c47ebce-462e-4637-a97d-30a5e246d254]

[cid:468ab5c1-7897-4fe7-81ef-6b29c522fbf8]

________________________________

**Comment by tartanguru** [comment]
I can't see those images I'm afraid - you'll need to upload them via the github page rather than by email

**Comment by liam4244** [comment]
https://accounts.google.com/o/oauth2/auth?access_type=offline&client_id=139695797394-4hs2a5slij42ugfjagj0vdmhkjp3l8r1.apps.googleusercontent.com&response_type=code&state=A2SAAEAEOgoqZSRcfSxbYRhMI_jQr8BsCWw4tpgqxKiiVJzW8Te-5W_7JOgSW4Q48NakyEqfIlDpnRybJBDtEdEy2h6A4juSbk0wB1LgR8dvh_JFNeznjcTsrhpqzMfZXGnrWWVVMQH-0GCR482PrdNlNeAJ6Qr_iif5o7TN235_iQJdfP97Laa30p4qak268SeEKRr3pjnGfxl0JDtY42v0v9pcdQj62KdD_HHaD0BLsVSwIKtyDAp4E8us7u7IAiZC1JzeFVEeYzsk7NvO86jq5SkW8txzZ0KRpOJFNZ-UHw4Y08MY-9gyPwSzSnKdC17ZsiLyKt_DzFTOWyjd28RLc2D9XuPyJsNxfoWZU5kAXnGJplQf6-o8vuNFzB8VZY3NY0iUC_UNS955a3r08A49RG8qjv_jHosoUYGJHlWBW4FPYrur2qX2-1JhjX9tS6RRhM-uCVO-cWg6Pulp2QFLDChC4Nu69gfnWiqgzIJIiZDbNYPLnAHwp1_CtUFkAEQNMNm2JSSJPSaLmdsFW_rir83BYI7JI9AOoADH2DwXZMoVECwt2gyUJtklWHYer2ZxaEQXAyvz5wxhN1zYhdQsy6w99dEmw&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fassistant-sdk-prototype+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fscript.external_request&redirect_uri=https%3A%2F%2Flayla.amazon.com%2Fapi%2Fskill%2Flink%2FM2Q2V3A50XW48V

**Comment by tartanguru** [comment]
Double check that you have copied over your client ID and secret into the right places. Also make sure that you have not put any extra spaces before or after. I'd also recommend editing the comment above to remove the link as it contains the details of your lambda function

**Comment by liam4244** [comment]
hi I have now been able to link the account. thanks for your help. the very last point where you need to download google assistant app.. why do you need to change the language to german?

**Comment by tartanguru** [comment]
Ah that's just a typo - you only need to change the language if want
something different that what the skill detects

**Comment by liam4244** [comment]
last question I promise. do you need to download the google assistant app for iphone though or is it good to go without?

**Comment by tartanguru** [comment]
It will work, but it will probably think you live in North Virginia or
Dublin. You can give it your exact location using the app

**Comment by liam4244** [comment]
Hi there. Sorry but it’s not working .. I linked the accounts that worked fine and completed the steps and it says I need to link the account. The skill has gone on to the app but will not work

Sent from my iPhone

On 1 Mar 2018, at 17:00, Ross Atkin <notifications@github.com<mailto:notifications@github.com>> wrote:

It will work, but it will probably think you live in North Virginia or
Dublin. You can give it your exact location using the app

**Comment by tartanguru** [comment]
Sorry - I don't understand what the issue is?

Are you saying that the link account button won't work?
If you are then try this:-


   1. Go to the Alexa web app and log in alexa.amazon.com
   2. Select "Skills" from the Home menu on the right hand side of the
   screen

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/home_skills.jpg>

   1. Click on "Your Skills" at the top right

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/your_skills.jpg>

   1. Click on "Dev Skills"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/dev_skills.jpg>

   1. Click on the skill called "Google Assistant for Alexa"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/assistant_skill.jpg>

   1. Click on "Disable Skill"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/disable_skill.jpg>

   1. Now click on "Enable Skill"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/enable_skill.jpg>

   1. Select the Google account you want to use and then make sure you
   click "Allow" on the Google authorisation page.

**Comment by liam4244** [comment]
Perfect it’s working now. I have it set up to England United Kingdom language and location and works well

Sent from my iPhone

On 1 Mar 2018, at 17:34, Ross Atkin <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry - I don't understand what the issue is?

Are you saying that the link account button won't work?
If you are then try this:-


1. Go to the Alexa web app and log in alexa.amazon.com<http://alexa.amazon.com>
2. Select "Skills" from the Home menu on the right hand side of the
screen

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/home_skills.jpg>

1. Click on "Your Skills" at the top right

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/your_skills.jpg>

1. Click on "Dev Skills"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/dev_skills.jpg>

1. Click on the skill called "Google Assistant for Alexa"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/assistant_skill.jpg>

1. Click on "Disable Skill"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/disable_skill.jpg>

1. Now click on "Enable Skill"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/enable_skill.jpg>

1. Select the Google account you want to use and then make sure you
click "Allow" on the Google authorisation page.

**Comment by liam4244** [comment]
Hi Ross,

Just noticed that it’s asking me to re link the account hourly. How can I stop this happening?

Sent from my iPhone

On 1 Mar 2018, at 17:34, Ross Atkin <notifications@github.com<mailto:notifications@github.com>> wrote:

Sorry - I don't understand what the issue is?

Are you saying that the link account button won't work?
If you are then try this:-


1. Go to the Alexa web app and log in alexa.amazon.com<http://alexa.amazon.com>
2. Select "Skills" from the Home menu on the right hand side of the
screen

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/home_skills.jpg>

1. Click on "Your Skills" at the top right

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/your_skills.jpg>

1. Click on "Dev Skills"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/dev_skills.jpg>

1. Click on the skill called "Google Assistant for Alexa"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/assistant_skill.jpg>

1. Click on "Disable Skill"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/disable_skill.jpg>

1. Now click on "Enable Skill"

[image: alt text]
<https://github.com/tartanguru/alexa-assistant-instructions/blob/master/screenshots/enable_skill.jpg>

1. Select the Google account you want to use and then make sure you
click "Allow" on the Google authorisation page.

**Comment by tartanguru** [comment]
Have a look at the common problems section - it tells you how to fix it

**Comment by liam4244** [comment]
I fixed that problem. But I have now accidentally removed the Alexa assistant as a device from the google assistant app on my phone. How do I add it back on?

Sent from my iPhone

On 1 Mar 2018, at 19:31, Ross Atkin <notifications@github.com<mailto:notifications@github.com>> wrote:

Have a look at the common problems section - it tells you how to fix it

**Comment by mahmoudjamal1** [comment]
Hello.
I'm having smiler issue When I try linking the account it takes me to sign in with my google account. I do that then click allow. It loads but then I get an error message saying 
"Amazon Alexa
We were unable to link Google Assistant for Alexa at this time.
For instructions and assistance with configuring your skill for account linking with OAuth, please see this guide."
